### ISSUE TITLE
Exception when trying to retrieve stats.

### ISSUE THREAD

**Issue by FeraruSilviuMarian** [JakeMakesStuff/aiofortnite#1]
An exception is thrown when I'm trying to retrieve the stats, witch means everything else works up until that point, what's the problem ? 
PS: The previous version of my code used The Python Fortnite API Wrapper, and it worked fine (so tokens and all that are fine) except the token got timed out, and instead of making a time-based interval function call to try to fix it, I decided to use this lib instead. 
        ```
        try:
            # TODO
            user = await fortnite.get_user(username);
            print('user object succesfully retrieved for', user.username, "line:", lineno()) # TODO
            # TODO
            stats = await user.stats.get(mode=None, platform=aiofortnite.Platforms.pc) # ERORR
            print('stats object succesfully retrieved', 'line:', lineno()) # TODO 
            print(stats, lineno())
        except:
            print(errorNotFound, 'line:', lineno())
            await client.send_message(message.channel, mentionPrefix + errorNotFound)
            return
```

**Comment by xinitrc-dev** [comment]
Here's more info about this issue:
File "..\Python36\lib\site-packages\aiofortnite\abc.py", line 166, in get
    ThreadPoolExecutor(), non_async_get
  File "..\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "..\Python36\lib\site-packages\aiofortnite\abc.py", line 126, in non_async_get
    cursor = self.db.cursor()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 13244 and this is thread id 19448

**Comment by bushshrub** [comment]
Seems to be an issue [here](https://github.com/JakeMakesStuff/aiofortnite/blob/master/aiofortnite/client.py#L52)

```
Traceback (most recent call last):
  File "C:\Users\Robert\Documents\GitHub\fnbstatsbot\aiofortnite\client.py", line 52, in get_user
    self.tokens.access_token
TypeError: __aexit__() got an unexpected keyword argument 'headers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robert\Documents\GitHub\fnbstatsbot\venv\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:/Users/Robert/Documents/GitHub/fnbstatsbot/bot.py", line 40, in on_message
    await get_user_stats(client, message, epic_displayname=messagecontents[0])
  File "C:\Users\Robert\Documents\GitHub\fnbstatsbot\commands\fortnite_cmds.py", line 26, in get_user_stats
    user = await fortnite_cli.get_user("Ninja")
  File "C:\Users\Robert\Documents\GitHub\fnbstatsbot\aiofortnite\client.py", line 52, in get_user
    self.tokens.access_token
TypeError: 'traceback' object is not callable
```
Python 3.6.6

SelfRenewingTokens class does not have an access_token. Hmm

**Comment by oconstrutor** [comment]
This project are dead ? still getting this same error...

**Comment by bushshrub** [comment]
Yes, project seems to be dead. Maybe the epic API has changed

**Comment by oconstrutor** [comment]
It seems that the token got outdate...

With this one seems to work 

`"CLIENT LAUNCHER TOKEN" => "MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE="

"FORTNITE CLIENT TOKEN" => "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="`

**Comment by Bluenix2** [comment]
Yes, my token also got dead recently. I've been looking around and those tokens work. I myself am thinking of making my own wrapper as both PFAW and Aiofortnite seems to be abandoned.
